/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package daniel.noel.informatiklk;

/**
 *
 * @author danie
 */
public class AB09_GroessterGemeinsamerTeiler extends javax.swing.JFrame {

    /**
     * Creates new form AB09_GroessterGemeinsamerTeiler
     */
    public AB09_GroessterGemeinsamerTeiler() {
        initComponents();
        this.setLocationRelativeTo(null);  //Fenster in der Mitte des Bildschirms öffnen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        infoLabel1 = new javax.swing.JLabel();
        inputField1 = new javax.swing.JTextField();
        inputField2 = new javax.swing.JTextField();
        infoLabel2 = new javax.swing.JLabel();
        outputInfoLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        calculateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setBackground(new java.awt.Color(0, 255, 0));
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Größter gemeinsamer Teiler");

        infoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel1.setText("Trage deine erste Zahl hier ein:");

        inputField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputField1ActionPerformed(evt);
            }
        });

        inputField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputField2ActionPerformed(evt);
            }
        });

        infoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel2.setText("Trage deine zweite Zahl hier ein:");

        outputInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        outputInfoLabel.setText("Dein Ergebnis lautet:");

        outputLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        outputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel.setForeground(new java.awt.Color(150, 150, 150));
        jLabel.setText("AB09_Rekursion");

        calculateButton.setText("Berechnen");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputField2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(outputInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(calculateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputInfoLabel))
                .addGap(16, 16, 16)
                .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputField1ActionPerformed

    private void inputField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputField2ActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        try {
            // Eingaben aus den Textfeldern lesen und in Integer umwandeln
            int zahl1 = Integer.parseInt(inputField1.getText());
            int zahl2 = Integer.parseInt(inputField2.getText());

            // Überprüfen, ob die Eingaben positiv sind
            if (zahl1 < 0 || zahl2 < 0) {
                outputLabel.setText("Nur positive Zahlen!");
                return;
            }

            // Berechnen des ggT
            int ggT = berechneGGT(zahl1, zahl2);

            // Anzeigen des Ergebnisses
            outputLabel.setText(String.valueOf(ggT));
        } catch (NumberFormatException e) {
            // Fehlerbehandlung für ungültige Eingaben
            outputLabel.setText("Ungültige Eingabe");
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    // Rekursive Methode zur Berechnung des größten gemeinsamen Teilers
    private int berechneGGT(int a, int b) {
        if (b == 0) {
            return a;
        } else {
            return berechneGGT(b, a % b);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AB09_GroessterGemeinsamerTeiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AB09_GroessterGemeinsamerTeiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AB09_GroessterGemeinsamerTeiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AB09_GroessterGemeinsamerTeiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AB09_GroessterGemeinsamerTeiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JTextField inputField1;
    private javax.swing.JTextField inputField2;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel outputInfoLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
